version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src/:/app
      - ./logs/php-error.log:/var/log/error.log
      - ./logs/php-access.log:/var/log/access.log
    networks:
      - bridge
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8000:80
      - 5173:5173
    volumes:
      - ./src/:/app
    depends_on:
      - app
    networks:
      - bridge

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_development
      MYSQL_USER: db-user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - bridge

networks:
  bridge:
    driver: bridge

volumes:
  mysql-volume:
